services:
  app:
    container_name: challenge-koibanx-app
    build:
      context: ../../
      dockerfile: ./docker/local/Dockerfile
    command: yarn run test
    restart: always
    env_file:
      - ../../.envs/.local/.api
    volumes:
      - ../../src:/app/src
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    container_name: challenge-koibanx-mongo
    image: mongo:7.0.16
    restart: unless-stopped
    env_file:
      - ../../.envs/.local/.mongo
    ports:
      - '27017:27017'
    networks:
      - backend

  redis:
    container_name: challenge-koibanx-redis
    image: redis:7.0.10
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: bridge
