services:
  app:
    container_name: challenge-koibanx-app
    build:
      context: ../../
      dockerfile: ./docker/local/Dockerfile
    command: yarn run dev
    restart: always
    env_file:
      - ../../.envs/.local/.api
    volumes:
      - ../../src:/app/src
    ports:
      - '3000:3000'
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    container_name: challenge-koibanx-mongodb
    image: mongo:7.0.16
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=challenge
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    container_name: challenge-koibanx-redis
    image: redis:7.0.10
    restart: unless-stopped
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
